baseURL: 'https://frienradar.com'
languageCode: 'en-us'
defaultContentLanguage: 'en'
title: 'Frienradar | Radar for nearby friends'
theme: 'PaperModX'
googleAnalytics: "G-DLJSYMN0PJ"
enableRobotsTXT: true

languages:
  en:
    languageName: 'English'
    weight: 1
    profileMode:
      enabled: true
      subtitle: "Available at 5/15/23"
      imageUrl: "images/icon.png" # optional
      imageTitle: "Frienradar App" # optional
      imageWidth: 220 # custom size
      imageHeight: 220 # custom size
      buttons:
        - name: Merchandise ðŸš€
          url: "https://www.teepublic.com/user/frienradar-app"


    menu:
#      main:
#        - name: Functionality
#          url: how-does-it-work
#          weight: 30
      footer:
        - name: Terms & Conditions
          url: terms-conditions
          weight: 5
        - name: Imprint
          url: imprint
          weight: 5
        - name: Privacy
          url: privacy
          weight: 5

  de:
    languageName: 'Deutsch'
    title: 'Frienradar | Radar fÃ¼r Personen in deiner Umgebung.'
    weight: 2
    profileMode:
      enabled: true
      subtitle: "VerfÃ¼gbar ab 15.5.23"
      imageUrl: "images/icon.png" # optional
      imageTitle: "Frienradar App" # optional
      imageWidth: 220 # custom size
      imageHeight: 220 # custom size
      buttons:
        - name: Merchandise ðŸš€
          url: "https://www.teepublic.com/user/frienradar-app"

    menu:
#      main:
#        - name: FunktionalitÃ¤t
#          url: how-does-it-work
#          weight: 30
      footer:
        - name: Nutzungsbedingungen
          url: terms-conditions
          weight: 5
        - name: Impressum
          url: imprint
          weight: 5
        - name: Datenschutz
          url: privacy
          weight: 5
  fr:
    languageName: 'FranÃ§ais'
    title: 'Frienradar | Radar pour personnes autour de vous.'
    subtitle: "Disponible de 15.5.23"
    weight: 2
    profileMode:
      enabled: true
      subtitle: "Disponible Ã  partir du 15.5.23"
      imageUrl: "images/icon.png" # optional
      imageTitle: "Frienradar App" # optional
      imageWidth: 220 # custom size
      imageHeight: 220 # custom size
      buttons:
        - name: Merchandise ðŸš€
          url: "https://www.teepublic.com/user/frienradar-app"

    menu:
      main:
        - name: FonctionnalitÃ©
          url: how-does-it-work
          weight: 30
      footer:
        - name: Terms et Conditions
          url: terms-conditions
          weight: 5
        - name: Imprint
          url: imprint
          weight: 5
        - name: Protection des donnÃ©es
          url: privacy
          weight: 5

params:
  env: 'production'
  TocSide: 'left'
  logo:
    text: 'Frienradar'
    icon: 'images/icon.png'
    iconHeight: 32
